{"name": "test_faile", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "def test_faile():\n>       assert False\nE       assert False\n\nTest_allureDemo1.py:9: AssertionError"}, "start": 1595240038920, "stop": 1595240038920, "uuid": "f1ba4717-12fb-4daa-8770-af74ec6e21dc", "historyId": "33a287a39a1136656b173072507a7097", "testCaseId": "9b3d073e70046a05c91999f2c1cb9f38", "fullName": "Test_allureDemo1#test_faile", "labels": [{"name": "suite", "value": "Test_allureDemo1"}, {"name": "host", "value": "DESKTOP-8222JDF"}, {"name": "thread", "value": "5124-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Test_allureDemo1"}]}