{"name": "test_login_failure", "status": "failed", "statusDetails": {"message": "AssertionError: assert '1' == 1", "trace": "self = <Test_allure_Login.TestLogin object at 0x000001F0DD402828>\n\n    @allure.story('密码缺失')\n    def test_login_failure(self):\n        with allure.step('点击用户名'):\n            print('请输入用户名')\n        with allure.step('点击密码'):\n            print('请输入密码')\n        print('点击登录')\n        with allure.step('点击登录之后登录失败'):\n>           assert '1' == 1\nE           AssertionError: assert '1' == 1\n\nTest_allure_Login.py:45: AssertionError"}, "steps": [{"name": "点击用户名", "status": "passed", "start": 1595241661262, "stop": 1595241661263}, {"name": "点击密码", "status": "passed", "start": 1595241661263, "stop": 1595241661263}, {"name": "点击登录之后登录失败", "status": "failed", "statusDetails": {"message": "AssertionError: assert '1' == 1\n", "trace": "  File \"D:\\Hogwarts\\Python_allure\\Test_allure_Login.py\", line 45, in test_login_failure\n    assert '1' == 1\n"}, "start": 1595241661263, "stop": 1595241661263}], "attachments": [{"name": "stdout", "source": "e927aec1-4ac5-4957-aa15-f466477fe018-attachment.txt", "type": "text/plain"}], "start": 1595241661262, "stop": 1595241661263, "uuid": "5d30e9ae-3254-465a-bee7-bfaba4c7b086", "historyId": "b22bef38acb5a3ac6439eb291be306c5", "testCaseId": "50493b578d57604db12c54a07c57c339", "fullName": "Test_allure_Login.TestLogin#test_login_failure", "labels": [{"name": "story", "value": "密码缺失"}, {"name": "feature", "value": "登录模块"}, {"name": "suite", "value": "Test_allure_Login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-8222JDF"}, {"name": "thread", "value": "4740-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Test_allure_Login"}]}